### ISSUE TITLE
C2A Reference をいい感じに自動展開できるようにする

### ISSUE THREAD

**Issue by meltingrabbit** [ut-issl/c2a-reference#1]
C2AはdoxygenにてReferenceを自動生成できる．それをcoreやsampleのdev or mainの更新に応じて，自動で更新し，展開できるようにする．

**Comment by meltingrabbit** [comment]
いい感じのactionsテンプレートを探すか

**Comment by meltingrabbit** [comment]
https://github.com/marketplace?type=actions&verification=verified_creator&query=doxygen

ない，だと．．．

よくわからないcreatorのはあるな．テンプレート使わずに愚直にやるか．

**Comment by meltingrabbit** [comment]
https://github.com/ut-issl/c2a-reference/blob/main/.github/workflows/generate_c2a_core_reference.yml でつくった．

![image](https://user-images.githubusercontent.com/39541984/144001131-d69bab7e-1dc4-4922-b272-260ef46e6c62.png)
なんか階層が変．もしかして，シンボリックリンクで無限ループになってるからとか？

２重にcloneして，とかのほうが良いか．

**Comment by meltingrabbit** [comment]
![image](https://user-images.githubusercontent.com/39541984/144002155-b9324c8d-e19a-44ae-ac08-c9bee6076589.png)

なおった．めでたし．

**Comment by sksat** [comment]
GitHub Pages，`docs/`みたいなかんじで実際にデプロイされるところを別ブランチにもできるので，mainの履歴が荒れて困りそうだったらそうするといいですよ．あと，commit authorは人間じゃなくてもいいんじゃないかな(実際その操作は人間がやっているわけではないし)．

**Comment by meltingrabbit** [comment]
> 実際にデプロイされるところを別ブランチにもできるので，mainの履歴が荒れて困りそうだったらそうするといいですよ

たしかに．work flowとかreadmeの更新をmainでやりつつ，別ブランチでhtmlをpush，で，mainが更新あったらmain→そのブランチ（たとえば， pages とか？）にマージ，がよさそう

**Comment by meltingrabbit** [comment]
>commit authorは人間じゃなくてもいいんじゃないかな

それちょっと思ったんだけど，実在しない名前，アドレスでいいの？それとも管理用アカウント取る感じ？

**Comment by sksat** [comment]
Renovateとかは`bot@renovateapp.com`みたいなやつにしてますし，GitHub Actionsからcommitする時は`github-actions[bot]@users.noreply.github.com`を使いがちですね．アイコンがGitHub Actionsのやつになるし． > commit author

**Comment by sksat** [comment]
です．mainは人間が書くやつ(index.htmlとかworkflowとか)だけを貯める場所にすればいい > ブランチ

**Comment by meltingrabbit** [comment]
まじか，そんなあどれすあったのね．

https://github.com/actions/checkout/discussions/479

それにします．

**Comment by sksat** [comment]
あと，`html`ってパス要らないのでは？

**Comment by meltingrabbit** [comment]
doxygenが勝手に作っちゃうんだよね．ちょっと見てみます．

**Comment by sksat** [comment]
あーなるほどそういうことか．他の場所に別のものを生成しないならmvしちゃえばよさそう

**Comment by meltingrabbit** [comment]
> 他の場所に別のものを生成しないならmvしちゃえばよさそう

そうね．１つのディレクトリに全部吐き出してるだけだし．

**Comment by meltingrabbit** [comment]
![image](https://user-images.githubusercontent.com/39541984/144099766-95f4ec06-84a6-4717-a0a1-27e6a1a20e15.png)

いい感じ

**Comment by meltingrabbit** [comment]
cronいれてないが，まあ一旦このissueの役目はおわったのでcloseしよう
