### ISSUE TITLE
status_updated.jsonが生成されていない？

### ISSUE THREAD

**Issue by sksat** [ut-issl/c2a-reference#15]
## 概要
`status_updated.json`が生成されておらず，status badgeが機能していない

## 必要な作業
- [x] workflow確認する
- [x] jsonがちゃんと生成されるようにする

**Comment by sksat** [comment]
これ原因分かった．`git commit -am`がダメ

**Comment by sksat** [comment]
`-am`ではトラッキングされてないファイルはstageされないんだな．普段`-am`使わないので知らなかった．

**Comment by meltingrabbit** [comment]
あ～，たしかにそうかも

**Comment by meltingrabbit** [comment]
status_updated.json ，readmeには使われてなかったから気づかなかったんか

**Comment by sksat** [comment]
むしろREADMEにしか使われていないのでは

**Comment by meltingrabbit** [comment]
あれ，勘違いしてた．ってか `resource not found` になってるじゃん

あれ～～～これ普通に動いてた気がしてたけど，なにか幻覚を見てたっぽいな．
