### ISSUE TITLE
READMEに，Referenceのもととなったリビジョンと更新日のバッジをいれる

### ISSUE THREAD

**Issue by meltingrabbit** [ut-issl/c2a-reference#3]
## 概要
READMEに，Referenceのもととなったリビジョンと更新日のバッジをいれる

## 詳細
https://shields.io/endpoint をつかいたい

## close条件
できたら

**Comment by sksat** [comment]
実際にREADMEに入ってはいないのでreopen
 https://github.com/ut-issl/c2a-reference/pull/5#pullrequestreview-822944311_
